{% set name = "opentelemetry-instrumentation-wsgi" %}
{% set version = "0.30b0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-instrumentation-wsgi-{{ version }}.tar.gz
  sha256: 34a058cff101420a1b4807020539fc18dc5967f4adf04935774507b10b848911

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - opentelemetry-api ~=1.3
    - opentelemetry-instrumentation ==0.30b0
    - opentelemetry-semantic-conventions ==0.30b0
    - opentelemetry-util-http ==0.30b0
    - python >=3.6
    # - opentelemetry-test ==0.24b0
    # - opentelemetry-test-utils ==0.26b1
    # - opentelemetry-test-utils ==0.27b0
    # - opentelemetry-test-utils ==0.28b0
    # - opentelemetry-test-utils ==0.28b1
    # - opentelemetry-test-utils ==0.29b0
    # - opentelemetry-test-utils ==0.30b0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-wsgi
  summary: WSGI Middleware for OpenTelemetry
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
