{% set name = "opentelemetry-instrumentation-wsgi" %}
{% set version = "0.26b1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-instrumentation-wsgi-{{ version }}.tar.gz
  sha256: 43ab3d78487f82a8a0f9c2be3d21b5920621712027e3fea756ba05039a6a3521

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - opentelemetry-api ~=1.3
    - opentelemetry-instrumentation ==0.26b1
    - opentelemetry-semantic-conventions ==0.26b1
    - opentelemetry-util-http ==0.26b1
    - python >=3.6
    # - opentelemetry-test ==0.24b0
    # - opentelemetry-test-utils ==0.26b1

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-wsgi
  summary: WSGI Middleware for OpenTelemetry
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
